theme = 'digio-theme'
title = "portfolio"

baseURL = 'https://portfolio.akanni.dev/'
languageCode = 'en-US'
# title = '˚₊‧꒰ა welcome to my Personal Website ໒꒱ ‧₊˚'
#22222
[menus]
  [[menus.main]]
    name = 'home'
    pageRef = '/'
    weight = 1
    [menus.main.params]
      image = '/digigarden2025.png'

  [[menus.main]]
    name = 'my links'
    pageRef = '/my_links'
    weight = 2


  [[menus.main]]
    name = 'about me'
    pageRef = '/hobbies'
    weight = 3

    [[menus.main]]
    name = 'open source 🗿'
    pageRef = '/open_source'
    weight = 4

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'

